version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install   # if Node.js app
  build:
    commands:
      - echo "Build started"
      - npm run build # or relevant build commands
artifacts:
  files:
    - '**/*'
  discard-paths: yes
