version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static site"

  build:
    commands:
      - echo "No build commands for static files"

artifacts:
  files:
    - index.html
    - scripts/**/*
    - aar_logo_final.png
    - README.md
