version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - cd frontend          # <- change this to your actual folder
      - npm install
  build:
    commands:
      - echo "Building app"
      - npm run build
artifacts:
  files:
    - '**/*'
